Repository SnailyCAD/fivem-integrations, pull requests merged in 2023-08, with the labels that each got.

#87 feat: user API token authentication flow
  .gitignore
  CHANGELOG.md
  integrations/sync/client/client.ts
  integrations/sync/fxmanifest.lua
  integrations/sync/nui-dev/index.html
  integrations/sync/nui-dev/package.json
  integrations/sync/nui-dev/pnpm-lock.yaml
  integrations/sync/nui-dev/postcss.config.js
  integrations/sync/nui-dev/src/authentication.ts
  integrations/sync/nui-dev/src/fetch.client.ts
  integrations/sync/nui-dev/src/main.ts
  integrations/sync/nui-dev/styles/main.css
  integrations/sync/nui-dev/tailwind.config.js
  integrations/sync/nui-dev/tsconfig.json
  integrations/sync/server/server.ts
  package.json
  src/utils/fetch.server.ts
  src/utils/get-player-ids.server.ts
Labels: enhancement

#91 feat: able to attach to 911 calls
  integrations/sync/client/client.ts
  integrations/sync/client/flows/911-call-attach.ts
  integrations/sync/nui-dev/index.html
  integrations/sync/nui-dev/package.json
  integrations/sync/nui-dev/pnpm-lock.yaml
  integrations/sync/nui-dev/src/flows/911-call-attach.ts
  integrations/sync/nui-dev/src/main.ts
  integrations/sync/nui-dev/src/utils/slate-data-to-string.ts
  integrations/sync/server/flows/911-call-attach.ts
  integrations/sync/server/server.ts
  src/types/events.ts
Labels: ✨ enhancement

#95 feat: traffic stop command
  integrations/sync/client/client.ts
  integrations/sync/client/flows/traffic-stop.ts
  integrations/sync/server/flows/traffic-stop.ts
  integrations/sync/server/server.ts
  src/types/events.ts
  src/utils/fetch.server.ts
Labels: 📚 documentation, ✨ enhancement

#99 feat: auto off duty (optional feature)
  integrations/sync/server/flows/unit-status.ts
Labels: 📚 documentation, ✨ enhancement

#101 chore: further publishable packages
  integrations/alpr/client/client.ts
  integrations/sync/client/client.ts
  integrations/sync/nui-dev/index.html
  integrations/sync/nui-dev/package.json
  integrations/sync/nui-dev/pnpm-lock.yaml
  integrations/sync/nui-dev/src/flows/911-call-attach.ts
  integrations/sync/nui-dev/src/flows/notification.ts
  integrations/sync/nui-dev/src/main.ts
  integrations/sync/nui-dev/src/utils/slate-data-to-string.ts
  integrations/sync/nui-dev/styles/main.css
  package.json
  pnpm-lock.yaml
  src/types/events.ts
Labels: dependencies
